services:
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #   depends_on:
  #     - backend
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - client-side
  backend:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: ./cmd/server/Dockerfile.dev
    volumes:
      - ./backend:/app
    container_name: shadershare_backend
    hostname: shadershare_backend
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres?sslmode=disable
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - ENVIRON=${ENVIRON}
      - AUTH_BASE_URL=${AUTH_BASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      # - JWT_SECRET=739e03884297c1e8e976
      # - REDIS_URL=redis:6379
      # - REDIS_SECRET=9F63929B4DE348EE76F452EEE9526
    networks:
      - localnet
  # redis:
  #   image: bitnami/redis:latest
  #   container_name: shadershader_redis
  #   volumes:
  #     - ./data:/bitnami/redis/data
  #   networks:
  #     - localnet
  #   ports:
  #     - 6379:6379
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - localnet

  migrate: &basemigrate
    container_name: migrate
    build:
      context: ./backend
    profiles: ["tools"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - localnet
    image: migrate/migrate
    entrypoint:
      ["migrate", "-path", "/migrations", "-database", "${DATABASE_URL}"]
    command: up
    links:
      - db
    volumes:
      - ./backend/db/migrations:/migrations
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres?sslmode=disable
  migrate-create:
    <<: *basemigrate
    entrypoint: migrate create -dir /migrations -ext sql
    command: ""
  database-reset:
    <<: *basemigrate
    command: ["drop", "-f"]

volumes:
  pgdata:
networks:
  localnet:
    driver: bridge
  client-side:
