// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RenderPass struct {
	ID        uuid.UUID
	ShaderID  uuid.UUID
	Code      string
	PassIndex int32
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Shader struct {
	ID            uuid.UUID
	Title         string
	Description   pgtype.Text
	UserID        uuid.UUID
	AccessLevel   int16
	PreviewImgUrl pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Username  string
	Email     string
	AvatarUrl pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
