// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: shader.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countShaders = `-- name: CountShaders :one
SELECT COUNT(*)
FROM shaders
WHERE
    (user_id = $1 OR $1 IS NULL) AND
    (access_level = $2 OR $2 IS NULL)
`

type CountShadersParams struct {
	UserID      pgtype.UUID
	AccessLevel pgtype.Int2
}

func (q *Queries) CountShaders(ctx context.Context, arg CountShadersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countShaders, arg.UserID, arg.AccessLevel)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShader = `-- name: CreateShader :one
INSERT INTO shaders (
    title, description, user_id, preview_img_url, access_level
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (title) DO NOTHING
RETURNING id, title, description, user_id, access_level, preview_img_url, created_at, updated_at
`

type CreateShaderParams struct {
	Title         string
	Description   pgtype.Text
	UserID        uuid.UUID
	PreviewImgUrl pgtype.Text
	AccessLevel   int16
}

func (q *Queries) CreateShader(ctx context.Context, arg CreateShaderParams) (Shader, error) {
	row := q.db.QueryRow(ctx, createShader,
		arg.Title,
		arg.Description,
		arg.UserID,
		arg.PreviewImgUrl,
		arg.AccessLevel,
	)
	var i Shader
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.AccessLevel,
		&i.PreviewImgUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShader = `-- name: DeleteShader :one
DELETE FROM shaders
WHERE id = $1 AND user_id = $2 RETURNING id, title, description, user_id, access_level, preview_img_url, created_at, updated_at
`

type DeleteShaderParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteShader(ctx context.Context, arg DeleteShaderParams) (Shader, error) {
	row := q.db.QueryRow(ctx, deleteShader, arg.ID, arg.UserID)
	var i Shader
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.AccessLevel,
		&i.PreviewImgUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShader = `-- name: GetShader :one
SELECT id, title, description, user_id, access_level, preview_img_url, created_at, updated_at FROM shaders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetShader(ctx context.Context, id uuid.UUID) (Shader, error) {
	row := q.db.QueryRow(ctx, getShader, id)
	var i Shader
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.AccessLevel,
		&i.PreviewImgUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShaderWithUser = `-- name: GetShaderWithUser :one
SELECT id, title, description, user_id, access_level, preview_img_url, created_at, updated_at, username FROM shader_with_user s
WHERE s.id = $1
`

func (q *Queries) GetShaderWithUser(ctx context.Context, id uuid.UUID) (ShaderWithUser, error) {
	row := q.db.QueryRow(ctx, getShaderWithUser, id)
	var i ShaderWithUser
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.AccessLevel,
		&i.PreviewImgUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const getUserShaderList = `-- name: GetUserShaderList :many
SELECT id, title, description, user_id, access_level, preview_img_url, created_at, updated_at FROM shaders 
WHERE user_id = $1
LIMIT $2 OFFSET $3
`

type GetUserShaderListParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetUserShaderList(ctx context.Context, arg GetUserShaderListParams) ([]Shader, error) {
	rows, err := q.db.Query(ctx, getUserShaderList, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shader
	for rows.Next() {
		var i Shader
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.AccessLevel,
			&i.PreviewImgUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShaders = `-- name: ListShaders :many
SELECT id, title, description, user_id, access_level, preview_img_url, created_at, updated_at FROM shaders
WHERE access_level = $3
ORDER BY id LIMIT $1 OFFSET $2
`

type ListShadersParams struct {
	Limit       int32
	Offset      int32
	AccessLevel int16
}

func (q *Queries) ListShaders(ctx context.Context, arg ListShadersParams) ([]Shader, error) {
	rows, err := q.db.Query(ctx, listShaders, arg.Limit, arg.Offset, arg.AccessLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shader
	for rows.Next() {
		var i Shader
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.AccessLevel,
			&i.PreviewImgUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShaders4 = `-- name: ListShaders4 :many
SELECT id, title, description, user_id, access_level, preview_img_url, created_at, updated_at
FROM shaders
WHERE 
  (user_id = $1 OR $1 IS NULL) AND
  (access_level = $2 OR $2 IS NULL)
ORDER BY updated_at DESC
LIMIT $4::int
OFFSET $3::int
`

type ListShaders4Params struct {
	UserID      pgtype.UUID
	AccessLevel pgtype.Int2
	Off         int32
	Lim         pgtype.Int4
}

func (q *Queries) ListShaders4(ctx context.Context, arg ListShaders4Params) ([]Shader, error) {
	rows, err := q.db.Query(ctx, listShaders4,
		arg.UserID,
		arg.AccessLevel,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shader
	for rows.Next() {
		var i Shader
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.AccessLevel,
			&i.PreviewImgUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShadersDetailed = `-- name: ListShadersDetailed :many
SELECT sd.id, sd.title, sd.description, sd.user_id, sd.access_level, sd.preview_img_url, sd.created_at, sd.updated_at, sd.outputs
FROM shader_details sd
WHERE 
  (user_id = $1 OR $1 IS NULL) AND
  (access_level = $2 OR $2 IS NULL)
ORDER BY sd.updated_at DESC
LIMIT $4::int
OFFSET $3::int
`

type ListShadersDetailedParams struct {
	UserID      pgtype.UUID
	AccessLevel pgtype.Int2
	Off         int32
	Lim         pgtype.Int4
}

func (q *Queries) ListShadersDetailed(ctx context.Context, arg ListShadersDetailedParams) ([]ShaderDetail, error) {
	rows, err := q.db.Query(ctx, listShadersDetailed,
		arg.UserID,
		arg.AccessLevel,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShaderDetail
	for rows.Next() {
		var i ShaderDetail
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.AccessLevel,
			&i.PreviewImgUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Outputs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShadersDetailedWithUser = `-- name: ListShadersDetailedWithUser :many
SELECT 
sd.id, sd.title, sd.description, sd.user_id, sd.access_level, sd.preview_img_url, sd.created_at, sd.updated_at, sd.outputs, sd.username from shader_details_with_user sd
JOIN users u ON sd.user_id = u.id
WHERE 
  (access_level = $1 OR $1 IS NULL)
ORDER BY sd.updated_at DESC
LIMIT $3::int
OFFSET $2::int
`

type ListShadersDetailedWithUserParams struct {
	AccessLevel pgtype.Int2
	Off         pgtype.Int4
	Lim         pgtype.Int4
}

func (q *Queries) ListShadersDetailedWithUser(ctx context.Context, arg ListShadersDetailedWithUserParams) ([]ShaderDetailsWithUser, error) {
	rows, err := q.db.Query(ctx, listShadersDetailedWithUser, arg.AccessLevel, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShaderDetailsWithUser
	for rows.Next() {
		var i ShaderDetailsWithUser
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.AccessLevel,
			&i.PreviewImgUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Outputs,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShadersWithUser = `-- name: ListShadersWithUser :many
SELECT s.id, s.title, s.description, s.user_id, s.access_level, s.preview_img_url, s.created_at, s.updated_at, s.username
FROM shader_with_user s
WHERE 
  (s.access_level = $1 OR $1 IS NULL)
ORDER BY CASE
    WHEN NOT $2::boolean AND $3::text = 'updated_at' THEN updated_at
    WHEN NOT $2::boolean AND $3::text = 'title' THEN title
END ASC, CASE 
    WHEN $2::boolean AND $3::text = 'updated_at' THEN updated_at
    WHEN $2::boolean AND $3::text = 'title' THEN title
END DESC
LIMIT $5::int
OFFSET $4::int
`

type ListShadersWithUserParams struct {
	AccessLevel pgtype.Int2
	Reverse     bool
	OrderBy     string
	Off         int32
	Lim         pgtype.Int4
}

func (q *Queries) ListShadersWithUser(ctx context.Context, arg ListShadersWithUserParams) ([]ShaderWithUser, error) {
	rows, err := q.db.Query(ctx, listShadersWithUser,
		arg.AccessLevel,
		arg.Reverse,
		arg.OrderBy,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShaderWithUser
	for rows.Next() {
		var i ShaderWithUser
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.AccessLevel,
			&i.PreviewImgUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShader = `-- name: UpdateShader :one
UPDATE shaders 
SET title = COALESCE(NULLIF($3::TEXT,''), title),
    description = COALESCE($4, description),
    preview_img_url = COALESCE($5, preview_img_url),
    access_level = COALESCE($6, access_level)
WHERE id = $1 AND user_id = $2
RETURNING id, title, description, user_id, access_level, preview_img_url, created_at, updated_at
`

type UpdateShaderParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Column3       string
	Description   pgtype.Text
	PreviewImgUrl pgtype.Text
	AccessLevel   int16
}

func (q *Queries) UpdateShader(ctx context.Context, arg UpdateShaderParams) (Shader, error) {
	row := q.db.QueryRow(ctx, updateShader,
		arg.ID,
		arg.UserID,
		arg.Column3,
		arg.Description,
		arg.PreviewImgUrl,
		arg.AccessLevel,
	)
	var i Shader
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.AccessLevel,
		&i.PreviewImgUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
